Repository OCA/vertical-isp, pull requests merged in 2019-10, with the labels that each got.

#27 [ADD] Connector Equipment
  connector_equipment/README.rst
  connector_equipment/__init__.py
  connector_equipment/__manifest__.py
  connector_equipment/models/__init__.py
  connector_equipment/models/backend_equipment.py
  connector_equipment/models/maintenance_equipment.py
  connector_equipment/readme/CONFIGURE.rst
  connector_equipment/readme/CONTRIBUTORS.rst
  connector_equipment/readme/DESCRIPTION.rst
  connector_equipment/readme/USAGE.rst
  connector_equipment/security/ir.model.access.csv
  connector_equipment/views/backend_equipment.xml
  connector_equipment/views/maintenance_equipment.xml
Labels: approved, enhancement, needs review

#32 [ADD] Connector Equipment Service
  connector_equipment_service/README.rst
  connector_equipment_service/__init__.py
  connector_equipment_service/__manifest__.py
  connector_equipment_service/models/__init__.py
  connector_equipment_service/models/agreement_serviceprofile.py
  connector_equipment_service/models/maintenance_equipment.py
  connector_equipment_service/readme/CONFIGURE.rst
  connector_equipment_service/readme/CONTRIBUTORS.rst
  connector_equipment_service/readme/DESCRIPTION.rst
  connector_equipment_service/readme/USAGE.rst
  connector_equipment_service/static/description/icon.png
  connector_equipment_service/static/description/index.html
  oca_dependencies.txt
Labels: enhancement, needs review

#10 [7.0] split invoicing into parts
  contract_isp_invoice/contract.py
Labels: needs review

#41 [IMP] Travis and README
  .travis.yml
  README.md
Labels: enhancement

#42 [12.0][IMP] connector_equipment
  connector_equipment/__manifest__.py
  connector_equipment/demo/backend_equipment_demo.xml
  connector_equipment/models/backend_equipment.py
  connector_equipment/views/backend_equipment.xml
Labels: approved
